server:
  port: 7001
spring:
  application:
    name: HMRJR-USER-SERVER
eureka:
  client:
    service-url:
      defaultZone: http://10.0.0.109:8761/eureka/

#    enabled: true
#  instance:
#    healthCheckUrlPath: ${server.servletPath}/health
#    statusPageUrlPath: ${server.servletPath}/info
#    homePageUrl: ${server.servletPath}/
#    healthcheck:
#      enabled: true



